### ISSUE TITLE
MiNT support?

### ISSUE THREAD

**Issue by danboid** [simonlaszcz/gulam#8]
Is gulam 0.2.0 supposed to work under Atari freemint or is it TOS only? I have not been able to get it to run as the INIT program under the latest freemint. If it is supposed to work under freemint too I can send you a screenshot of the errors I get.

Please can you make gulams support (or lack of it) for MiNT clear in the README?

Thanks

**Comment by simonlaszcz** [comment]
It's TOS only

**Comment by danboid** [comment]
Thanks Simon.
